---
grafana_version: "10.0.2"  
grafana_url: "https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.linux-amd64.tar.gz"
grafana_install_dir: "/usr/local/bin"
grafana_config_src: "roles/monitoring/templates/grafana.ini.j2"  
grafana_config_dest: "/etc/grafana/grafana.ini"
grafana_service_src: "roles/monitoring/templates/grafana.service.j2"  
grafana_service_dest: "/etc/systemd/system/grafana.service"
alertmanager_version: "0.22.2" 
alertmanager_url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
alertmanager_install_dir: "/usr/local/bin"
alertmanager_config_src: "roles/monitoring/files/alertmanager.yml"  
alertmanager_config_dest: "/etc/alertmanager/alertmanager.yml"
alertmanager_service_src: "roles/monitoring/templates/alertmanager.service.j2"  
alertmanager_service_dest: "/etc/systemd/system/alertmanager.service"
