---
- name: Install required packages for Grafana on Debian/Ubuntu
  ansible.builtin.package:
    name:
      - apt-transport-https
      - unzip
    state: present
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Install required packages for Grafana on Red Hat/CentOS
  ansible.builtin.package:
    name:
      - unzip
    state: present
  when: ansible_distribution in ['RedHat', 'CentOS']

- name: Download Grafana binary
  get_url:
    url: "{{ grafana_url }}"
    dest: "/tmp/grafana-{{ grafana_version }}.linux-amd64.tar.gz"

- name: Extract Grafana binary
  unarchive:
    src: "/tmp/grafana-{{ grafana_version }}.linux-amd64.tar.gz"
    dest: "{{ grafana_install_dir }}"
    remote_src: yes
    creates: "{{ grafana_install_dir }}/grafana-{{ grafana_version }}"

- name: Create Grafana configuration directory
  file:
    path: "/etc/grafana/"
    state: directory

- name: Copy Grafana configuration file
  copy:
    src: "grafana.ini.j2"
    dest: "{{ grafana_config_dest }}"

- name: Create Grafana service file
  copy:
    src: "grafana.service.j2"
    dest: "{{ grafana_service_dest }}"

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start Grafana service and enable it on boot
  service:
    name: "{{ grafana_service_name }}"
    state: started
    enabled: yes
